# Generated by Django 3.0.7 on 2020-06-24 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cachorros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200)),
                ('Raca', models.CharField(max_length=200)),
                ('Genero', models.CharField(max_length=200)),
                ('Cor', models.CharField(max_length=200)),
                ('Idade', models.CharField(max_length=2)),
                ('Vacinacao', models.CharField(max_length=3)),
                ('Observacoes', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200)),
                ('Raca', models.CharField(max_length=200)),
                ('Genero', models.CharField(max_length=200)),
                ('Cor', models.CharField(max_length=200)),
                ('Idade', models.CharField(max_length=2)),
                ('Vacinacao', models.CharField(max_length=3)),
                ('Observacoes', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='petPerdido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200)),
                ('Raca', models.CharField(max_length=200)),
                ('Genero', models.CharField(max_length=200)),
                ('Cor', models.CharField(max_length=200)),
                ('Idade', models.CharField(max_length=2)),
                ('Data', models.CharField(max_length=200)),
                ('Local', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='petAchado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200)),
                ('Data', models.CharField(max_length=200)),
                ('Local', models.CharField(max_length=200)),
                ('Observacoes', models.CharField(max_length=400, null=True)),
                ('Cor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.petPerdido')),
            ],
        ),
    ]
