# Generated by Django 3.0.7 on 2020-06-24 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20200624_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petachado',
            name='Nome',
        ),
        migrations.AddField(
            model_name='petachado',
            name='Genero',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petachado',
            name='Raca',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='petEncontrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDono', models.CharField(max_length=200)),
                ('Nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.petPerdido')),
            ],
        ),
    ]
