# Generated by Django 3.0.7 on 2020-06-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20200624_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200)),
                ('Nascimento', models.CharField(max_length=200)),
                ('Genero', models.CharField(max_length=200)),
                ('Idade', models.CharField(max_length=2)),
                ('Contato', models.CharField(max_length=600)),
                ('ONG', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='petencontrado',
            old_name='nomeDono',
            new_name='Dono',
        ),
        migrations.AddField(
            model_name='petachado',
            name='Contato',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petperdido',
            name='Contato',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petperdido',
            name='Dono',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
