# Generated by Django 3.0.7 on 2020-06-24 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20200624_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cachorros',
            new_name='Cachorro',
        ),
        migrations.RenameModel(
            old_name='Gatos',
            new_name='Gato',
        ),
        migrations.AddField(
            model_name='petachado',
            name='Nome',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petachado',
            name='Voluntario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.Voluntario'),
        ),
    ]
